### ISSUE TITLE
funny/smart public README

### ISSUE THREAD

**Issue by navanjr** [inkbird-io/.github#1]

**Comment by Isaac-with-Inkbird** [comment]
How's this?
----

Inkbird is a tech start-up in the Midwest, specializing in design, web development, and storytelling.

We create meaningful tools and resources for our clients. Our goal is to deliver assets our customers will be proud of for years to come. 

Whether its a story that’s written or coded; something experienced with a controller in hand or with a bowl of popcorn; Inkbird is crafting properties that will stick around for a long time.

**Comment by navanjr** [comment]
great i love it.... cheater.

**Comment by navanjr** [comment]
you should commit that.

**Comment by Isaac-with-Inkbird** [comment]
Cheater?

**Comment by Isaac-with-Inkbird** [comment]
How do I comment?

**Comment by navanjr** [comment]
You used chat GPT didn't you.

**Comment by Isaac-with-Inkbird** [comment]
No, I wrote that a few days ago

**Comment by navanjr** [comment]
`commit` not comment

**Comment by navanjr** [comment]
https://github.com/inkbird-io/.github/edit/main/README.md

**Comment by Isaac-with-Inkbird** [comment]
Where do I do that?

**Comment by navanjr** [comment]
use this link: https://github.com/inkbird-io/.github/edit/main/README.md

**Comment by navanjr** [comment]
@Isaac-with-Inkbird were you able to edit the README and commit your changes to the `main` branch?
